apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

secretGenerator:
  - name: env
    type: Opaque
    behavior: replace
    envs:
      - ./secrets.env

configMapGenerator:
  - name: env
    behavior: replace
    envs:
      - ./settings.env
