# Generated by Django 4.2.10 on 2024-02-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalab_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataoperation',
            name='cache_key',
            field=models.CharField(blank=True, default='', help_text='Cache key for this operation', max_length=64),
        ),
    ]
