# Generated by Django 4.2.9 on 2024-02-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalab_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataoperation',
            name='message',
            field=models.CharField(blank=True, default='', help_text='Contextual message related to this DataOperation', max_length=200),
        ),
        migrations.AddField(
            model_name='dataoperation',
            name='percent_complete',
            field=models.IntegerField(default=0, help_text='Completion status (in percent) of this DataOperation'),
        ),
        migrations.AddField(
            model_name='dataoperation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', help_text='Status of this DataOperation', max_length=20),
        ),
    ]
