# Generated by Django 4.2.25 on 2025-10-09 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalab_session', '0002_dataoperation_cache_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataoperation',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='datasession',
            options={'ordering': ['-modified']},
        ),
    ]
