# Generated by Django 4.2.30 on 2026-09-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalab_session', '0003_alter_dataoperation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasession',
            name='persist',
            field=models.BooleanField(default=False, verbose_name='Persist this datasession beyond 30 days'),
        ),
    ]
