# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/deployment-apps-v1.json

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
    spec:
      securityContext:
        fsGroup: 1
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 128Mi
      containers:
        - name: default
          image: datalab
          securityContext:
            runAsNonRoot: true
            runAsUser: 1
            runAsGroup: 1
            readOnlyRootFilesystem: true
          command:
            - gunicorn
            - --bind=0.0.0.0:8080
            - --worker-class=gevent
            - --workers=$(GUNICORN_WORKERS)
            - --timeout=$(GUNICORN_TIMEOUT)
            - --user=daemon
            - --group=daemon
            - --access-logfile=-
            - --error-logfile=-
            - datalab.wsgi
          env:
            - name: GUNICORN_WORKERS
              value: "2"
            - name: GUNICORN_TIMEOUT
              value: "300"
          envFrom:
            - configMapRef:
                name: env
                optional: false
            - secretRef:
                name: env
                optional: false
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: tmp
              mountPath: /tmp
              readOnly: false
          livenessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 3
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 3
            httpGet:
              path: /
              port: http
