# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/deployment-apps-v1.json

apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app.kubernetes.io/component: worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
      containers:
        - name: default
          image: datalab
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          command:
            - "python"
            - "manage.py"
            - "rundramatiq"
            - "--processes" 
            - "2"
            - "--threads"
            - "4"
          envFrom:
            - configMapRef:
                name: env
                optional: false
            - secretRef:
                name: env
                optional: false
          volumeMounts:
            - name: tmp
              mountPath: /tmp
              readOnly: false
          livenessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 30
            exec:
              command:
                - /bin/true
