apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deploy-server.yaml
  - ./svc-server.yaml
  - ./deploy-static.yaml
  - ./svc-static.yaml
  - ./pv.yaml
  - ./pvc.yaml
  - ./deploy-worker.yaml

labels:
  - pairs:
      app.kubernetes.io/name: datalab
    includeSelectors: true

secretGenerator:
  - name: env
    type: Opaque

configMapGenerator:
  - name: env
