apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-tmp-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/"