kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: worker-tmp-pvc
spec:
  volumeName: worker-tmp-pv
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
