name: Django Test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry env info
        poetry install
    - name: Run Tests
      run: |
        poetry run python manage.py test
