name: Django Test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Start virtual enviorment
      run: |
        python3 -m venv venv
        source venv/bin/activate
    - name: Install Poetry
      run: |
        python3 -m pip install poetry
    - name: Install Django
      run: |
        python3 -m pip install django
    - name: Install Dependencies
      run: |
        poetry install --no-interaction --no-root
    - name: Run Tests
      run: |
        python3 manage.py test
